version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: testeleo
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
    links:
      - database
    ports:
      - '3000:3000'

  database:
    image: postgres
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
